### ISSUE TITLE
Create a way to pull in the number of comments per Github issue once per day

### ISSUE THREAD

**Issue by eunicekokor** [codeforamerica/gotissues#11]
#### Description

Now that we have a way to look at all the clicked issues from Google Analytics, we want to see some stats about how many issues have comments on them (one of our measurements of activity on an issue). Then look a little deeper into comments relate to activities elsewhere in the project.
#### Example

The Github API's response for any issue's comments if it has more than 1 looks like this. We want to specifically get and store the number of comments, who commented, and anything else that might help us understand how commenting on the issue helps with having activity.
## Other info that will be useful
- [ ] If people who are commenting on the issue have commented before in the project
- [x] Timestamps

`https://api.github.com/repos/codeforamerica/gotissues/issues/5/comments`

```
[
  {
    url: "https://api.github.com/repos/codeforamerica/gotissues/issues/comments/112017994",
    html_url: "https://github.com/codeforamerica/gotissues/issues/5#issuecomment-112017994",
    issue_url: "https://api.github.com/repos/codeforamerica/gotissues/issues/5",
    id: 112017994,
    user: {
    login: "sbenthall",
    id: 68752,
    avatar_url: "https://avatars.githubusercontent.com/u/68752?v=3",
    gravatar_id: "",
    url: "https://api.github.com/users/sbenthall",
    html_url: "https://github.com/sbenthall",
    followers_url: "https://api.github.com/users/sbenthall/followers",
    following_url: "https://api.github.com/users/sbenthall/following{/other_user}",
    gists_url: "https://api.github.com/users/sbenthall/gists{/gist_id}",
    starred_url: "https://api.github.com/users/sbenthall/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/sbenthall/subscriptions",
    organizations_url: "https://api.github.com/users/sbenthall/orgs",
    repos_url: "https://api.github.com/users/sbenthall/repos",
    events_url: "https://api.github.com/users/sbenthall/events{/privacy}",
    received_events_url: "https://api.github.com/users/sbenthall/received_events",
    type: "User",
    site_admin: false
  },
  created_at: "2015-06-15T10:59:51Z",
  updated_at: "2015-06-15T10:59:51Z",
  body: "Re: "Top Ten Clicked Issues", see https://github.com/codeforamerica/gotissues/issues/3#issuecomment-112017032 I think this data would be more meaningful if it was normalized somehow against its prominence on the Civic Issue Finder site. So a good endpoint (if it can be collected from Google Analytics...maybe it would require some hacking on the UI to get GA to pick it up) would be "Number of times issues have been displayed on the front page (and in what order)." "
  },
  {
    url: "https://api.github.com/repos/codeforamerica/gotissues/issues/comments/112181287",
    html_url: "https://github.com/codeforamerica/gotissues/issues/5#issuecomment-112181287",
    issue_url: "https://api.github.com/repos/codeforamerica/gotissues/issues/5",
    id: 112181287,
    user: {
     login: "eunicekokor",
     id: 5273390,
     avatar_url: "https://avatars.githubusercontent.com/u/5273390?v=3",
     gravatar_id: "",
     url: "https://api.github.com/users/eunicekokor",
     html_url: "https://github.com/eunicekokor",
     followers_url: "https://api.github.com/users/eunicekokor/followers",
     following_url: "https://api.github.com/users/eunicekokor/following{/other_user}",
     gists_url: "https://api.github.com/users/eunicekokor/gists{/gist_id}",
     starred_url: "https://api.github.com/users/eunicekokor/starred{/owner}{/repo}",
     subscriptions_url: "https://api.github.com/users/eunicekokor/subscriptions",
     organizations_url: "https://api.github.com/users/eunicekokor/orgs",
     repos_url: "https://api.github.com/users/eunicekokor/repos",
     events_url: "https://api.github.com/users/eunicekokor/events{/privacy}",
     received_events_url: "https://api.github.com/users/eunicekokor/received_events",
     type: "User",
     site_admin: false
  },
    created_at: "2015-06-15T19:30:25Z",
    updated_at: "2015-06-15T19:30:25Z",
    body: "Another related thing I realized, too, was that some issues are getting more face time on some sites. For example, only SF Brigade projects are shown on the Code for San Fransisco page, so it might be useful to look at the number of times the issue has been displayed on each page the widget exists if also possible?"
  },
  {
    url: "https://api.github.com/repos/codeforamerica/gotissues/issues/comments/112182450",
    html_url: "https://github.com/codeforamerica/gotissues/issues/5#issuecomment-112182450",
    issue_url: "https://api.github.com/repos/codeforamerica/gotissues/issues/5",
    id: 112182450,
    user: {
    login: "migurski",
    id: 58730,
    avatar_url: "https://avatars.githubusercontent.com/u/58730?v=3",
    gravatar_id: "",
    url: "https://api.github.com/users/migurski",
    html_url: "https://github.com/migurski",
    followers_url: "https://api.github.com/users/migurski/followers",
    following_url: "https://api.github.com/users/migurski/following{/other_user}",
    gists_url: "https://api.github.com/users/migurski/gists{/gist_id}",
    starred_url: "https://api.github.com/users/migurski/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/migurski/subscriptions",
    organizations_url: "https://api.github.com/users/migurski/orgs",
    repos_url: "https://api.github.com/users/migurski/repos",
    events_url: "https://api.github.com/users/migurski/events{/privacy}",
    received_events_url: "https://api.github.com/users/migurski/received_events",
    type: "User",
    site_admin: false
  },
  created_at: "2015-06-15T19:35:05Z",
  updated_at: "2015-06-15T19:35:05Z",
  body: ":+1: @eunicekokor "
  }
]
```
#### Tasks
- [x] Write a very clear route that can take in the list of issues and write random results to a file
- [x] Expand the method to run the script with the issues, specify w/ the data we want that we talked about above
- [x] Create/test a JSON "dump" file to write response results to
- [x] Learn about writing this auto-update script with Heroku
- [x] Implement the script with the route
- [ ] Test!
#### Files

run.py
New script to run by Heroku autoupdate
