### ISSUE TITLE
Create a way to look at Github "activity" for issues and their associated repositories.

### ISSUE THREAD

**Issue by eunicekokor** [codeforamerica/gotissues#12]
#### Description

We want to correlate somehow clicking on an issue through the Civic Issue Finder and seeing if that led to specific events taken by contributors. Github records all the data for specific actions. For example, when someone forks a repository, information about who forked it, what time it was forked, etc. gets associated with the repository. We want to see if there is an association between actions like forking and our clicks. 
#### Example

Here's a snippet of an action. We want data about the
- [x] timestamp list of when the project was starred
- [x] timestamp list of when the project was watched
- [x] timestamp list of when the project was forked
- [x] timestamp list of when the  project got a pull request
#### Notes

Need to look at the project events
look for "starredEvent", "watchedEvent", "forkedEvent" "PRevent"
and record the "created_at" time
More thinking about how we put into db since we want to relate times of these events in the project to time an issue within that project being clicked

`https://api.github.com/repos/codeforamerica/gotissues/events`

``````
[
  {
    id: "2913846125",
    type: "IssuesEvent",
    actor: {
      id: 5273390,
      login: "eunicekokor",
      gravatar_id: "",
      url: "https://api.github.com/users/eunicekokor",
      avatar_url: "https://avatars.githubusercontent.com/u/5273390?"
    },
    repo: {
      id: 30446370,
      name: "codeforamerica/gotissues",
      url: "https://api.github.com/repos/codeforamerica/gotissues"
    },
    payload: {
      action: "opened",
      issue: {
      url: "https://api.github.com/repos/codeforamerica/gotissues/issues/11",
      labels_url: "https://api.github.com/repos/codeforamerica/gotissues/issues/11/labels{/name}",
      comments_url: "https://api.github.com/repos/codeforamerica/gotissues/issues/11/comments",
      events_url: "https://api.github.com/repos/codeforamerica/gotissues/issues/11/events",
      html_url: "https://github.com/codeforamerica/gotissues/issues/11",
      id: 90234668,
      number: 11,
      title: "Create a way to pull in the number of comments per Github issue once per day",
      user: {
        login: "eunicekokor",
        id: 5273390,
        avatar_url: "https://avatars.githubusercontent.com/u/5273390?v=3",
        gravatar_id: "",
        url: "https://api.github.com/users/eunicekokor",
        html_url: "https://github.com/eunicekokor",
        followers_url: "https://api.github.com/users/eunicekokor/followers",
        following_url: "https://api.github.com/users/eunicekokor/following{/other_user}",
        gists_url: "https://api.github.com/users/eunicekokor/gists{/gist_id}",
        starred_url: "https://api.github.com/users/eunicekokor/starred{/owner}{/repo}",
        subscriptions_url: "https://api.github.com/users/eunicekokor/subscriptions",
        organizations_url: "https://api.github.com/users/eunicekokor/orgs",
        repos_url: "https://api.github.com/users/eunicekokor/repos",
        events_url: "https://api.github.com/users/eunicekokor/events{/privacy}",
        received_events_url: "https://api.github.com/users/eunicekokor/received_events",
        type: "User",
        site_admin: false
        },
        labels: [ ],
        state: "open",
        locked: false,
        assignee: null,
        milestone: null,
        comments: 0,
        created_at: "2015-06-22T22:53:49Z",
        updated_at: "2015-06-22T22:53:49Z",
        closed_at: null,
        body: "#### Description Now that we have a way to look at all the clicked issues from Google Analytics, we want to see some stats about how many issues have comments on them (one of our measurements of activity on an issue). Then look a little deeper into comments relate to activities elsewhere in the project. #### Example The Github API's response for any issue's comments if it has more than 1 looks like this. We want to specifically get and store the **starred** items and maybe other things if they seem to be useful for looking at what the properties of closed issues are! ## Other info that will be useful - [ ] If people who are commenting on the issue have commented before in the project - [ ] Timestamps `https://api.github.com/repos/codeforamerica/gotissues/issues/5/comments` ``` [ { url: "https://api.github.com/repos/codeforamerica/gotissues/issues/comments/112017994", html_url: "https://github.com/codeforamerica/gotissues/issues/5#issuecomment-112017994", issue_url: "https://api.github.com/repos/codeforamerica/gotissues/issues/5", id: 112017994, user: { login: "sbenthall", id: 68752, avatar_url: "https://avatars.githubusercontent.com/u/68752?v=3", gravatar_id: "", url: "https://api.github.com/users/sbenthall", html_url: "https://github.com/sbenthall", followers_url: "https://api.github.com/users/sbenthall/followers", following_url: "https://api.github.com/users/sbenthall/following{/other_user}", gists_url: "https://api.github.com/users/sbenthall/gists{/gist_id}", starred_url: "https://api.github.com/users/sbenthall/starred{/owner}{/repo}", subscriptions_url: "https://api.github.com/users/sbenthall/subscriptions", organizations_url: "https://api.github.com/users/sbenthall/orgs", repos_url: "https://api.github.com/users/sbenthall/repos", events_url: "https://api.github.com/users/sbenthall/events{/privacy}", received_events_url: "https://api.github.com/users/sbenthall/received_events", type: "User", site_admin: false }, created_at: "2015-06-15T10:59:51Z", updated_at: "2015-06-15T10:59:51Z", body: "Re: "Top Ten Clicked Issues", see https://github.com/codeforamerica/gotissues/issues/3#issuecomment-112017032 I think this data would be more meaningful if it was normalized somehow against its prominence on the Civic Issue Finder site. So a good endpoint (if it can be collected from Google Analytics...maybe it would require some hacking on the UI to get GA to pick it up) would be "Number of times issues have been displayed on the front page (and in what order)." " }, { url: "https://api.github.com/repos/codeforamerica/gotissues/issues/comments/112181287", html_url: "https://github.com/codeforamerica/gotissues/issues/5#issuecomment-112181287", issue_url: "https://api.github.com/repos/codeforamerica/gotissues/issues/5", id: 112181287, user: { login: "eunicekokor", id: 5273390, avatar_url: "https://avatars.githubusercontent.com/u/5273390?v=3", gravatar_id: "", url: "https://api.github.com/users/eunicekokor", html_url: "https://github.com/eunicekokor", followers_url: "https://api.github.com/users/eunicekokor/followers", following_url: "https://api.github.com/users/eunicekokor/following{/other_user}", gists_url: "https://api.github.com/users/eunicekokor/gists{/gist_id}", starred_url: "https://api.github.com/users/eunicekokor/starred{/owner}{/repo}", subscriptions_url: "https://api.github.com/users/eunicekokor/subscriptions", organizations_url: "https://api.github.com/users/eunicekokor/orgs", repos_url: "https://api.github.com/users/eunicekokor/repos", events_url: "https://api.github.com/users/eunicekokor/events{/privacy}", received_events_url: "https://api.github.com/users/eunicekokor/received_events", type: "User", site_admin: false }, created_at: "2015-06-15T19:30:25Z", updated_at: "2015-06-15T19:30:25Z", body: "Another related thing I realized, too, was that some issues are getting more face time on some sites. For example, only SF Brigade projects are shown on the Code for San Fransisco page, so it might be useful to look at the number of times the issue has been displayed on each page the widget exists if also possible?" }, { url: "https://api.github.com/repos/codeforamerica/gotissues/issues/comments/112182450", html_url: "https://github.com/codeforamerica/gotissues/issues/5#issuecomment-112182450", issue_url: "https://api.github.com/repos/codeforamerica/gotissues/issues/5", id: 112182450, user: { login: "migurski", id: 58730, avatar_url: "https://avatars.githubusercontent.com/u/58730?v=3", gravatar_id: "", url: "https://api.github.com/users/migurski", html_url: "https://github.com/migurski", followers_url: "https://api.github.com/users/migurski/followers", following_url: "https://api.github.com/users/migurski/following{/other_user}", gists_url: "https://api.github.com/users/migurski/gists{/gist_id}", starred_url: "https://api.github.com/users/migurski/starred{/owner}{/repo}", subscriptions_url: "https://api.github.com/users/migurski/subscriptions", organizations_url: "https://api.github.com/users/migurski/orgs", repos_url: "https://api.github.com/users/migurski/repos", events_url: "https://api.github.com/users/migurski/events{/privacy}", received_events_url: "https://api.github.com/users/migurski/received_events", type: "User", site_admin: false }, created_at: "2015-06-15T19:35:05Z", updated_at: "2015-06-15T19:35:05Z", body: ":+1: @eunicekokor " } ] ``` #### Tasks [ ] Write a very clear route that can take in the list of issues and write random results to a file [ ] Expand the method to run the script with the issues, specify w/ the data we want that we talked about above [ ] Create/test a JSON "dump" file to write response results to [ ] Learn about writing this auto-update script with Heroku [ ] Implement the script with the route [ ] Test! #### Files run.py New script to run by Heroku autoupdate"
        }
      },
    public: true,
    created_at: "2015-06-22T22:53:49Z",
  org: {
    id: 337792,
    login: "codeforamerica",
    gravatar_id: "",
    url: "https://api.github.com/orgs/codeforamerica",
    avatar_url: "https://avatars.githubusercontent.com/u/337792?"
  }
},
``````
#### Tasks
- [x] Write a very clear route that can take in the list of issues and write random results to a file
- [x] Expand the method to run the script with the issues, specify w/ the data we want that we talked about above
- [x] Create/test a JSON "dump" file to write response results to
- [x] Prioritize which information you want to save, some repositories might have a LOT of traffic
- [x] Implement the script with the route
- [x] Test!
#### Files

run.py
Other scripts

**Comment by eunicekokor** [comment]
Right now I'm starting to add to clocks.py to get the data described below
''' Activity end goals --> we want to look at timestamps of when issues were clicked
    then we want to look at the project it was a part of and check if there was
    activity within that time period (probably like 30-60 seconds). '''

''' I want to test it by the way it is on the heroku site, select an issue from a
    list of clicked issues (which we can sort by most recently clicked, and that is the
    only way to have the timestamp attached). Then it will return the time that issue was
    clicked, it's github status: (closed, open, last updated, etc), AND project events
    around the the time it was clicked. '''

''' Sample Flow:
        GET issues and list by recently clicked time (this is the default)
        Get this issue: https://github.com/codeforamerica/ohana-web-search/issues/221
        and the time it was clicked. (maybe into some dict)
        Call to GA and put the issue status and when it was last updated (into the same dict)
        Call to GA on the project the issue was in and if an event timestamp was in timedelta
        60 seconds from the time of the click (in the dict) then we add the event, the timedelta 
        of that event and the actor into that same dict then write dict to database'''

**Comment by eunicekokor** [comment]
This is a bit trickier and more time intensive because we have to look at all 8,0000 clicks

**Comment by eunicekokor** [comment]
++ I will need help in putting this into the db
right now we have a table of clicked issue IDs, and I'm thinking for each clicked issue we can have a clicks array or something which expands for like each click on this clicked issue, you know the time and if there was activity on that click or not

**Comment by eunicekokor** [comment]
After chatting our new goals for this will be to make a new table of clicks with columns that have columns like timestamps timestamp, issue_id int, nearby_events json. that json will have the title of the action(s) and the timestamp of that action
